# Generated by Django 6.1.1 on 2026-09-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_vaga', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=150)),
                ('modalidade', models.CharField(choices=[('Remoto', 'Remoto'), ('Híbrido', 'Híbrido'), ('Presencial', 'Presencial')], default='Remoto', max_length=20)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requisitos', models.TextField()),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
    ]
